[ADD] pirata_payroll_xlsx_report
odoo-ps/pshk-pirata pull request #26
Opened 2021-11-10 01:57 UTC by tong-odoo

2021-11-10 07:57 UTC, fja-odoo requested changes
Will they still need the PDF report after this ?
Not sure it makes much sense to have 2 separate reports for the same data ?

2021-11-10 14:15 UTC, fja-odoo requested changes

2021-11-10 14:15 UTC, fja-odoo commented on pirata_payroll_xlsx_report/models/hr_payslip.py
> +        attachment = self.env["ir.attachment"].create(
Why not put this in a controller and jut return a report without the attachment ?
The server action could return an act_url leading to that controller.
This way no need to store the attachment.
Same as hsbc autopay

2021-11-11 08:54 UTC, tong-odoo commented on pirata_payroll_xlsx_report/models/hr_payslip.py
> +        attachment = self.env["ir.attachment"].create(
I remembered we discuss this topic before but my memory is kind of fading. I believe since this one is the same as the pdf report so they might want to access it later. That's why I put them into an attachment instead. 
p.s. IDK I really can't remember but I am quite sure I did in this way for a reason :)

2021-11-11 09:40 UTC, fja-odoo commented on pirata_payroll_xlsx_report/models/hr_payslip.py
> +        attachment = self.env["ir.attachment"].create(
Hum, in that case this should be a document or linked to a model so they can find it back later. Check with Emily/Francis and if this is not needed I think it is best to not store it

2021-11-15 02:05 UTC, fja-odoo requested changes

2021-11-15 02:38 UTC, fja-odoo approved these changes

2021-11-15 02:50 UTC, merged